export const TOGGLE_SIGNUP_DRAWER = "TOGGLE_SIGNUP_DRAWER";
export const TOGGLE_LOGIN_DRAWER = "TOGGLE_LOGIN_DRAWER"
export const REGISTER_USER = "REGISTER_USER";
export const REQUEST = "REQUEST";
export const FAILED_REQUEST = "FAILED_REQUEST";