export const TOGGLE_SIGNUP_DRAWER = "TOGGLE_SIGNUP_DRAWER";
export const TOGGLE_LOGIN_DRAWER = "TOGGLE_LOGIN_DRAWER"
export const REGISTER_USER = "REGISTER_USER";
export const REQUEST = "REQUEST";
export const FAILED_USER_REQUEST = "FAILED_USER_REQUEST";
export const CLEARING_PROPS = "CLEARING_PROPS"