export const FETCH_MOVIE_REQUEST = "FETCH_GENERAL_RECOMMENDATIONS";
export const FETCH_GENERAL_RECOMMENDATIONS_SUCCESS = "FETCH_GENERAL_RECOMMENDATIONS_SUCCESS"
export const FAILED_REQUEST = "FAILED_REQUEST";

