export const FETCH_MOVIE_REQUEST = "FETCH_GENERAL_RECOMMENDATIONS";
export const FETCH_GENERAL_RECOMMENDATIONS_SUCCESS = "FETCH_GENERAL_RECOMMENDATIONS_SUCCESS"
export const FAILED_REQUEST = "FAILED_REQUEST";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const GET_ALL_TOP_MOVIES = "GET_ALL_TOP_MOVIES";